const { SlashCommandBuilder } = require('discord.js');
const jokes = [
    "Waarom kunnen geheimagenten nooit goed schaken? Omdat ze altijd bang zijn voor de loper!",
    "Waarom kunnen je tanden niet goed schaatsen? Omdat ze altijd in de verkeerde lijn staan!",
    "Waarom kunnen computers nooit goed schaken? Omdat ze altijd bang zijn voor de loper!",
    "Wat doet een olifant als hij een huiskat ziet? Hij zegt 'ik hou van je!'",
    "Waarom kunnen geheimagenten nooit goed schaken? Omdat ze altijd bang zijn voor de loper!",
    "Waarom kunnen je tanden niet goed schaatsen? Omdat ze altijd in de verkeerde lijn staan!",
    "Waarom kunnen computers nooit goed schaken? Omdat ze altijd bang zijn voor de loper!",
    "Wat doet een olifant als hij een huiskat ziet? Hij zegt 'ik hou van je!'",
    "Waarom ging de boom naar de dokter? Omdat hij zich niet goed voelde!",
    "Waarom hebben vissen altijd zo'n goed humeur? Omdat ze nooit uit hun slof schieten!",
    "Waarom kunnen eenden zo goed basketballen? Omdat ze altijd met hun eendenpoot scoren!",
    "Wat doet een sneeuwman in de zomer? Smelten!",
    "Waarom kunnen koeien geen muziek spelen? Omdat ze geen noot kunnen raken!",
    "Waarom kunnen krokodillen zo goed schaken? Omdat ze altijd de juiste zetten maken!",
    "Waarom hebben wolken geen oren? Omdat ze altijd overal op hun hoede zijn!",
    "Waarom kunnen katten niet goed schaken? Omdat ze altijd de stukken omduwen!",
    "Waarom kunnen apen nooit goed dansen? Omdat ze altijd de verkeerde beweging maken!",
    "Wat doet een olifant als hij de ruimte in wil? Hij neemt de lift!",
    "Waarom is de lucht blauw? Omdat de regen zich altijd verstopt!",
    "Waarom is de oceaan zo verdrietig? Omdat de zee altijd op het strand ligt!",
    "Waarom kunnen leeuwen nooit goed schaken? Omdat ze altijd de loper verplaatsen!",
    "Wat doet een hond in de sneeuw? Hij maakt sneeuwhoopjes!",
    "Waarom kunnen giraffen niet goed schaatsen? Omdat hun nek altijd in de weg zit!",
    "Wat zegt een muis als hij in de computer kruipt? 'Ik ben de byte!'",
    "Waarom ging de taart naar school? Omdat hij beter wilde leren!",
    "Waarom kunnen vissen niet goed schaken? Omdat ze geen handen hebben!",
    "Wat zegt een vis als hij uit het water komt? 'Hé, ik ben een vis!'",
    "Waarom kunnen mieren nooit goed schaatsen? Omdat ze altijd uit hun spoor lopen!",
    "Wat zegt een kip als ze niet kan vliegen? 'Ik ben gewoon een boer!'",
    "Waarom kunnen honden nooit goed schaken? Omdat ze altijd het bord omgooien!",
    "Wat zegt een konijn als hij in een boek zit? 'Dit is een leuke lees konijn!'",
    "Waarom kunnen varkens niet goed schaken? Omdat ze altijd de loper opeten!",
    "Waarom is de lucht zo blauw? Omdat de zon altijd probeert te schijnen!",
    "Waarom kunnen vissen niet goed schaken? Omdat ze altijd in de verkeerde richting zwemmen!",
    "Waarom zijn bananen zo gelukkig? Omdat ze altijd in de zon liggen!",
    "Waarom heeft een kip geen goede baan? Omdat ze altijd op het erf rondloopt!",
    "Waarom kunnen beren niet goed schaken? Omdat ze altijd de stukken opeten!",
    "Wat zegt een muis als hij zich verstopt? 'Ik ben aan het spelen!'",
    "Waarom kunnen schapen niet goed schaken? Omdat ze altijd de loper verliezen!",
    "Waarom kunnen apen nooit goed schaatsen? Omdat ze altijd op hun buik vallen!",
    "Waarom kunnen katten niet goed schaken? Omdat ze altijd de stukken omduwen!",
    "Waarom ging de eend naar de dokter? Omdat hij verkouden was!",
    "Waarom kunnen muizen niet goed schaken? Omdat ze altijd de stukken knagen!",
    "Waarom was de tafel zo verdrietig? Omdat hij zijn tafelpoten had verloren!",
    "Waarom hebben giraffen zulke lange nekken? Omdat ze de lucht niet willen missen!",
    "Waarom kan een hond niet schaken? Omdat hij altijd de stukken laat liggen!",
    "Waarom kunnen schildpadden nooit goed schaken? Omdat ze te langzaam zijn!",
    "Waarom kunnen vissen niet goed schaken? Omdat ze altijd de stukken uit het water halen!",
    "Waarom kunnen konijnen niet goed schaken? Omdat ze altijd de loper verliezen!",
    "Waarom kunnen giraffen niet goed schaken? Omdat ze de stukken niet kunnen zien!",
    "Waarom kan een muis niet goed schaken? Omdat hij altijd de stukken eet!",
    "Waarom kunnen koeien niet goed schaken? Omdat ze altijd de loper omduwen!",
    "Waarom gingen de vissen naar de dokter? Omdat ze ziek waren!",
    "Waarom is een kat altijd zo blij? Omdat hij altijd in de zon ligt!",
    "Waarom kunnen eenden niet goed schaken? Omdat ze altijd de stukken omduwen!",
    "Waarom kan een kat geen computer gebruiken? Omdat hij altijd op de toetsen drukt!",
    "Waarom kunnen schapen nooit goed schaken? Omdat ze altijd de loper verliezen!",
    "Waarom kunnen beren nooit goed schaken? Omdat ze altijd de stukken opeten!",
    "Waarom is de zee zo groot? Omdat de oceaan altijd probeert te ontsnappen!",
    "Waarom kunnen mieren nooit goed schaken? Omdat ze altijd uit hun spoor lopen!",
    "Waarom kunnen giraffen niet goed schaken? Omdat ze altijd de loper verliezen!",
    "Waarom kan een hond niet schaken? Omdat hij altijd de stukken omgooit!",
    "Waarom ging de hond naar de dokter? Omdat hij zich niet goed voelde!",
    "Waarom ging de kip naar de dokter? Omdat ze niet meer goed kon lopen!",
    "Waarom hebben giraffen lange nekken? Omdat ze altijd alles willen zien!",
    "Waarom ging de koe naar de dokter? Omdat hij last had van zijn maag!",
    "Waarom ging de muis naar de dokter? Omdat hij zijn stem kwijt was!",
    "Waarom kan een vogel niet schaken? Omdat hij altijd wegvliegt!",
    "Waarom kunnen honden niet goed schaken? Omdat ze altijd de stukken kwijtraken!",
    "Waarom is de lucht blauw? Omdat de regen zich altijd verstopt!",
    "Waarom kunnen vissen niet goed schaken? Omdat ze geen handen hebben!",
    "Waarom kunnen katten niet goed schaken? Omdat ze altijd de stukken omduwen!",
    "Waarom kunnen olifanten nooit goed schaken? Omdat ze altijd de loper missen!",
    "Waarom heeft een vos geen goede baan? Omdat hij altijd te snel is!",
    "Waarom kunnen giraffen niet goed schaken? Omdat ze de stukken niet kunnen zien!",
    "Waarom kunnen muizen niet goed schaken? Omdat ze altijd de stukken knagen!",
    "Waarom kunnen konijnen niet goed schaken? Omdat ze altijd de loper verliezen!",
    "Waarom heeft een kat zo'n lange staart? Omdat hij altijd de loper moet volgen!",
    "Waarom kan een hond geen schaken? Omdat hij altijd de stukken omgooit!",
    "Waarom is de oceaan zo groot? Omdat de vissen altijd de kant op zwemmen!",
    "Waarom kunnen varkens niet goed schaken? Omdat ze altijd de loper opeten!",
    "Waarom kunnen schapen niet goed schaken? Omdat ze altijd de stukken verliezen!",
    "Waarom ging de eend naar de dokter? Omdat hij verkouden was!",
    "Waarom kunnen apen nooit goed schaken? Omdat ze altijd de verkeerde stukken kiezen!",
    "Waarom heeft een koe geen goede baan? Omdat ze altijd in de wei is!",
    "Waarom ging de hond naar de dokter? Omdat hij pijn had!",
    "Waarom kunnen olifanten niet goed schaken? Omdat ze de stukken niet goed kunnen zien!",
    "Waarom kunnen apen niet goed schaken? Omdat ze altijd te veel spelen!",
    "Waarom is de lucht zo blauw? Omdat de regen zich altijd verstopt!",
    "Waarom kunnen wolken niet goed schaken? Omdat ze altijd overal op hun hoede zijn!",
    "Waarom kunnen vissen niet goed schaken? Omdat ze altijd in de verkeerde richting zwemmen!",
];

module.exports = {
    data: new SlashCommandBuilder()
        .setName('grap')
        .setDescription('Haal een grappige Nederlandse grap op!'),
    async execute(interaction) {
        const randomJoke = jokes[Math.floor(Math.random() * jokes.length)];
        await interaction.reply({ content: randomJoke });
    },
};
